-- ============================================================
-- STO Management — Sample Data for Analytics Dashboard
-- ============================================================
-- Run this in SSMS against your sto_management database.
-- All rows use STO IDs prefixed 'STO-DEMO-' so they won't
-- clash with data from npm run seed.
--
-- To remove this data later:
--   DELETE FROM sto_audit_log  WHERE sto_request_id IN (SELECT id FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%');
--   DELETE FROM sto_requests   WHERE sto_id LIKE 'STO-DEMO-%';
-- ============================================================

-- Covers:
--   • 12 months of data  (Jun 2025 → May 2026)
--   • 3 sites            (ABC, ABL, XYZ)
--   • All 8 statuses
--   • ~25% rush requests
--   • Varied material values ($2K–$52K)
--   • 6 different site-to-site routes
-- ============================================================


-- ── JUNE 2025 ────────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-001','2025-06-03',0,2,'ABC','ABC','ABL',0,1,'Alice Carter','alice.carter@company.com','MAT-D001','API Active Ingredient Batch R10',250,'KG','2-8C refrigerated',1,8500.00,950.00,1,'2025-06-15',0,1,2,'2025-06-04','Stock confirmed.',1,5,'2025-06-06','PO confirmed.','STO-ABC-25-011','SHP-25011',1,'2025-06-10','2025-06-12','TRK-DHL-001','2025-06-14',1,'COMPLETE','CLOSED','2025-06-14');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-002','2025-06-10',1,1,'ABL','ABL','XYZ',0,1,'Grace Kim','grace.kim@company.com','MAT-D002','Blister Foil 250mm — urgent',10000,'EA','Ambient keep dry',0,3200.00,420.00,0,'2025-06-13','Production line risk.',0,1,2,'2025-06-11','Approved.',1,5,'2025-06-12','OK.','STO-ABL-25-009','SHP-25009',1,'2025-06-12','2025-06-13','TRK-UPS-002','2025-06-14',1,'COMPLETE','CLOSED','2025-06-14');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-003','2025-06-18',0,2,'XYZ','XYZ','ABC',0,1,'Maria Evans','maria.evans@company.com','MAT-D003','Bulk Drug Substance Compound XR-50',75,'KG','-20C frozen dry ice',1,15000.00,2100.00,1,'2025-06-30',1,1,2,'2025-06-19','Cold chain confirmed.',1,4,'2025-06-21','Budget approved.',1,5,'2025-06-23','PO clear.','STO-XYZ-25-005','SHP-25005',1,'2025-06-25','2025-06-26','TRK-DHL-003','2025-06-28',1,'COMPLETE','CLOSED','2025-06-28');


-- ── JULY 2025 ─────────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-004','2025-07-07',0,2,'ABC','ABC','XYZ',0,1,'Alice Carter','alice.carter@company.com','MAT-D004','Compound XR-77 Drug Substance',50,'KG','-20C frozen',1,22000.00,3100.00,1,'2025-07-20',1,1,2,'2025-07-08','Available.',1,4,'2025-07-10','Approved.',1,5,'2025-07-12','Clear.','STO-ABC-25-018','SHP-25018',1,'2025-07-15','2025-07-16','TRK-FEDEX-004','2025-07-18',1,'COMPLETE','CLOSED','2025-07-18');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-005','2025-07-14',1,1,'ABL','ABL','ABC',0,1,'Henry Wu','henry.wu@company.com','MAT-D005','Packaging Components Cartons',5000,'EA','Ambient',0,4800.00,380.00,0,'2025-07-17','Urgent packaging needed.',0,1,2,'2025-07-15','OK.',1,5,'2025-07-16','Approved.','STO-ABL-25-014','SHP-25014',1,'2025-07-16','2025-07-17','TRK-UPS-005','2025-07-18',1,'COMPLETE','CLOSED','2025-07-18');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-006','2025-07-22',0,3,'XYZ','XYZ','ABL',0,1,'Olivia Reed','olivia.reed@company.com','MAT-D006','Excipient Microcrystalline Cellulose',1500,'KG','Ambient',0,9100.00,750.00,0,'2025-08-05',0,1,2,'2025-07-23','Confirmed.',1,5,'2025-07-25','OK.','STO-XYZ-25-008','SHP-25008',1,'2025-07-28','2025-07-29','TRK-DHL-006','2025-07-31',1,'COMPLETE','CLOSED','2025-07-31');


-- ── AUGUST 2025 ───────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-007','2025-08-05',0,2,'ABC','ABC','ABL',0,1,'Alice Carter','alice.carter@company.com','MAT-D007','API Batch R15',300,'KG','2-8C',1,11500.00,1200.00,1,'2025-08-18',0,1,2,'2025-08-06','Stock available.',1,5,'2025-08-09','Approved.','STO-ABC-25-024','SHP-25024',1,'2025-08-14','2025-08-15','TRK-DHL-007','2025-08-17',1,'COMPLETE','CLOSED','2025-08-17');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-008','2025-08-12',1,1,'XYZ','XYZ','ABC',0,1,'Rachel Tran','rachel.tran@company.com','MAT-D008','Stability Samples Q3',150,'EA','2-8C',1,7200.00,600.00,1,'2025-08-15','Stability deadline.',0,1,2,'2025-08-13','OK.',1,5,'2025-08-14','Approved.','STO-XYZ-25-012','SHP-25012',1,'2025-08-14','2025-08-15','TRK-FEDEX-008','2025-08-16',1,'COMPLETE','CLOSED','2025-08-16');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-009','2025-08-20',0,2,'ABL','ABL','XYZ',0,1,'Karen Bell','karen.bell@company.com','MAT-D009','Finished Goods Tablet 20mg',8000,'EA','Ambient',0,33000.00,3800.00,0,'2025-09-03',1,1,2,'2025-08-21','Confirmed.',1,4,'2025-08-24','Approved within budget.',1,5,'2025-08-27','PO raised.','STO-ABL-25-019','SHP-25019',1,'2025-08-29','2025-08-30','TRK-DHL-009','2025-09-01',1,'COMPLETE','CLOSED','2025-09-01');


-- ── SEPTEMBER 2025 ────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-010','2025-09-03',0,3,'ABC','ABC','XYZ',0,1,'Brian Scott','brian.scott@company.com','MAT-D010','Primary Packaging Vials 10mL',15000,'EA','Ambient fragile',0,5600.00,520.00,0,'2025-09-16',0,1,2,'2025-09-04','Available.',1,5,'2025-09-06','Approved.','STO-ABC-25-031','SHP-25031',1,'2025-09-10','2025-09-11','TRK-UPS-010','2025-09-13',1,'COMPLETE','CLOSED','2025-09-13');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-011','2025-09-10',1,1,'ABL','ABL','ABC',0,1,'James Ford','james.ford@company.com','MAT-D011','Compound YZ-12 High Value',40,'KG','-20C',1,18900.00,2700.00,1,'2025-09-15','Supply chain risk.',1,1,2,'2025-09-11','Confirmed.',1,4,'2025-09-13','Approved.',1,5,'2025-09-15','Signed off.','STO-ABL-25-022','SHP-25022',1,'2025-09-15','2025-09-16','TRK-DHL-011','2025-09-17',1,'COMPLETE','CLOSED','2025-09-17');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-012','2025-09-22',0,3,'XYZ','XYZ','ABL',0,1,'Nathan Cole','nathan.cole@company.com','MAT-D012','Lactose Monohydrate 200M',2000,'KG','Ambient',0,2400.00,310.00,0,'2025-10-05',0,1,2,'2025-09-23','OK.',1,5,'2025-09-26','Done.','STO-XYZ-25-017','SHP-25017',1,'2025-09-29','2025-09-30','TRK-FEDEX-012','2025-10-02',1,'COMPLETE','CLOSED','2025-10-02');


-- ── OCTOBER 2025 ──────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-013','2025-10-06',0,2,'ABC','ABC','ABL',0,1,'Alice Carter','alice.carter@company.com','MAT-D013','Drug Substance Batch DS-77',60,'KG','-20C dry ice',1,41500.00,6200.00,1,'2025-10-22',1,1,2,'2025-10-07','Stock confirmed.',1,4,'2025-10-10','High value approved.',1,5,'2025-10-13','PO raised and cleared.','STO-ABC-25-039','SHP-25039',1,'2025-10-17','2025-10-18','TRK-DHL-013','2025-10-20',1,'COMPLETE','CLOSED','2025-10-20');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-014','2025-10-14',1,1,'ABL','ABL','XYZ',0,1,'Leo Singh','leo.singh@company.com','MAT-D014','Reference Standards Q4',80,'EA','2-8C',1,6700.00,520.00,1,'2025-10-17','Stability programme deadline.',0,1,2,'2025-10-15','Approved.',1,5,'2025-10-16','OK.','STO-ABL-25-029','SHP-25029',1,'2025-10-16','2025-10-17','TRK-UPS-014','2025-10-18',1,'COMPLETE','CLOSED','2025-10-18');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-015','2025-10-24',0,2,'XYZ','XYZ','ABC',0,1,'Quinn Patel','quinn.patel@company.com','MAT-D015','Amber Vials 20mL',25000,'EA','Ambient fragile',0,13200.00,1100.00,0,'2025-11-07',0,1,2,'2025-10-25','Confirmed.',1,5,'2025-10-29','Approved.','STO-XYZ-25-021','SHP-25021',1,'2025-11-01','2025-11-02','TRK-DHL-015','2025-11-04',1,'COMPLETE','CLOSED','2025-11-04');


-- ── NOVEMBER 2025 ─────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-016','2025-11-04',0,3,'ABC','ABC','XYZ',0,1,'Carol White','carol.white@company.com','MAT-D016','Excipient PVP K30',800,'KG','Ambient',0,9800.00,780.00,0,'2025-11-18',0,1,2,'2025-11-05','OK.',1,5,'2025-11-08','Done.','STO-ABC-25-044','SHP-25044',1,'2025-11-12','2025-11-13','TRK-FEDEX-016','2025-11-15',1,'COMPLETE','CLOSED','2025-11-15');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,rejection_reason,status,updated_at)
VALUES ('STO-DEMO-2025-017','2025-11-10',0,3,'ABL','ABL','ABC',0,1,'Henry Wu','henry.wu@company.com','MAT-D017','Obsolete Solvent — Phase Out',200,'L','Ambient',0,4200.00,0.00,0,'2025-11-25',0,0,2,'2025-11-11','Material discontinued — no longer in inventory.','Material discontinued — cannot proceed.','REJECTED','2025-11-11');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-018','2025-11-18',1,1,'XYZ','XYZ','ABL',0,1,'Patrick James','patrick.james@company.com','MAT-D018','Controlled Substance Batch CS-03',20,'KG','-20C controlled',1,27500.00,4100.00,1,'2025-11-24','Regulatory submission deadline.',1,1,2,'2025-11-19','Confirmed available.',1,4,'2025-11-21','Approved urgently.',1,5,'2025-11-22','Cleared.','STO-XYZ-25-028','SHP-25028',1,'2025-11-23','2025-11-24','TRK-DHL-018','2025-11-25',1,'COMPLETE','CLOSED','2025-11-25');


-- ── DECEMBER 2025 ─────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-019','2025-12-03',0,2,'ABC','ABC','ABL',0,1,'Frank Lopez','frank.lopez@company.com','MAT-D019','API Batch R19',200,'KG','2-8C',1,7300.00,820.00,1,'2025-12-16',0,1,2,'2025-12-04','Available.',1,5,'2025-12-08','Approved.','STO-ABC-25-051','SHP-25051',1,'2025-12-12','2025-12-13','TRK-UPS-019','2025-12-15',1,'COMPLETE','CLOSED','2025-12-15');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-020','2025-12-09',0,2,'ABL','ABL','XYZ',0,1,'Karen Bell','karen.bell@company.com','MAT-D020','Finished Goods Tablet 5mg — Year End',12000,'EA','Ambient',0,52000.00,5800.00,0,'2025-12-22',1,1,2,'2025-12-10','Confirmed.',1,4,'2025-12-13','High value approved.',1,5,'2025-12-16','PO signed.','STO-ABL-25-037','SHP-25037',1,'2025-12-18','2025-12-19','TRK-DHL-020','2025-12-21',1,'COMPLETE','CLOSED','2025-12-21');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-021','2025-12-15',1,1,'XYZ','XYZ','ABC',0,1,'Rachel Tran','rachel.tran@company.com','MAT-D021','Stability Samples Year End',100,'EA','2-8C',1,3800.00,290.00,1,'2025-12-18','Year-end regulatory deadline.',0,1,2,'2025-12-16','OK.',1,5,'2025-12-17','Done.','STO-XYZ-25-034','SHP-25034',1,'2025-12-17','2025-12-18','TRK-FEDEX-021','2025-12-19',1,'COMPLETE','CLOSED','2025-12-19');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2025-022','2025-12-19',0,3,'ABC','ABC','XYZ',0,1,'Brian Scott','brian.scott@company.com','MAT-D022','Cellulose Tablets 100mg',3000,'EA','Ambient',0,16400.00,1400.00,0,'2026-01-05',0,1,2,'2025-12-20','Confirmed.',1,5,'2025-12-23','Approved.','STO-ABC-25-058','SHP-25058',1,'2025-12-28','2025-12-29','TRK-DHL-022','2025-12-31',1,'COMPLETE','CLOSED','2025-12-31');


-- ── JANUARY 2026 ──────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-001','2026-01-07',0,2,'ABL','ABL','ABC',0,1,'Henry Wu','henry.wu@company.com','MAT-D023','API Batch R21 — New Year',280,'KG','2-8C',1,8900.00,980.00,1,'2026-01-20',0,1,2,'2026-01-08','Available.',1,5,'2026-01-11','Approved.','STO-ABL-26-003','SHP-26003',1,'2026-01-15','2026-01-16','TRK-DHL-023','2026-01-18',1,'COMPLETE','CLOSED','2026-01-18');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-002','2026-01-13',1,1,'XYZ','XYZ','ABL',0,1,'Olivia Reed','olivia.reed@company.com','MAT-D024','High Value Compound ZX-99',35,'KG','-20C',1,24700.00,3600.00,1,'2026-01-18','Clinical trial supply.',1,1,2,'2026-01-14','Confirmed.',1,4,'2026-01-16','Approved.',1,5,'2026-01-17','PO OK.','STO-XYZ-26-006','SHP-26006',1,'2026-01-17','2026-01-18','TRK-FEDEX-024','2026-01-19',1,'COMPLETE','CLOSED','2026-01-19');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,rejection_reason,status,updated_at)
VALUES ('STO-DEMO-2026-003','2026-01-21',0,3,'ABC','ABC','ABL',0,1,'Alice Carter','alice.carter@company.com','MAT-D025','Discontinued Excipient Phase 2',500,'KG','Ambient',0,5500.00,0.00,0,'2026-02-05',0,0,2,'2026-01-22','Material on quality hold — transfer not permitted.','Quality hold in place — transfer blocked.','REJECTED','2026-01-22');


-- ── FEBRUARY 2026 ─────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-004','2026-02-04',0,2,'ABC','ABC','XYZ',0,1,'Carol White','carol.white@company.com','MAT-D026','API Intermediate Batch R23',320,'KG','2-8C',1,12300.00,1350.00,1,'2026-02-18',0,1,2,'2026-02-05','Stock confirmed.',1,5,'2026-02-09','Approved.','STO-ABC-26-014','SHP-26014',1,'2026-02-13','2026-02-14','TRK-DHL-026','2026-02-16',1,'COMPLETE','CLOSED','2026-02-16');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-005','2026-02-11',0,3,'ABL','ABL','XYZ',0,1,'Leo Singh','leo.singh@company.com','MAT-D027','Excipient Mannitol SD200',1200,'KG','Ambient',0,6100.00,490.00,0,'2026-02-25',0,1,2,'2026-02-12','OK.',1,5,'2026-02-15','Done.','STO-ABL-26-009','SHP-26009',1,'2026-02-19','2026-02-20','TRK-UPS-027','2026-02-22',1,'COMPLETE','CLOSED','2026-02-22');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-006','2026-02-19',1,1,'XYZ','XYZ','ABC',0,1,'Quinn Patel','quinn.patel@company.com','MAT-D028','Drug Substance Batch DS-91',55,'KG','-20C dry ice',1,38000.00,5500.00,1,'2026-02-25','Regulatory filing deadline.',1,1,2,'2026-02-20','Confirmed.',1,4,'2026-02-22','Approved — priority.',1,5,'2026-02-24','PO issued.','STO-XYZ-26-012','SHP-26012',1,'2026-02-24','2026-02-25','TRK-DHL-028','2026-02-26',1,'COMPLETE','CLOSED','2026-02-26');


-- ── MARCH 2026 ────────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-007','2026-03-03',0,2,'ABC','ABC','ABL',0,1,'Frank Lopez','frank.lopez@company.com','MAT-D029','API Batch R24',275,'KG','2-8C',1,9700.00,1050.00,1,'2026-03-17',0,1,2,'2026-03-04','Available.',1,5,'2026-03-08','OK.','STO-ABC-26-022','SHP-26022',1,'2026-03-12','2026-03-13','TRK-FEDEX-029','2026-03-15',1,'COMPLETE','CLOSED','2026-03-15');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-008','2026-03-10',0,3,'ABL','ABL','ABC',0,1,'James Ford','james.ford@company.com','MAT-D030','Tablet Coating Agent',600,'KG','Ambient',0,4400.00,350.00,0,'2026-03-24',0,1,2,'2026-03-11','OK.',1,5,'2026-03-14','Done.','STO-ABL-26-016','SHP-26016',1,'2026-03-18','2026-03-19','TRK-UPS-030','2026-03-21',1,'COMPLETE','CLOSED','2026-03-21');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-009','2026-03-17',1,1,'XYZ','XYZ','ABL',0,1,'Nathan Cole','nathan.cole@company.com','MAT-D031','Compound ZX-44 Clinical',30,'KG','-20C',1,18200.00,2600.00,1,'2026-03-23','Clinical batch urgent.',1,1,2,'2026-03-18','Confirmed.',1,4,'2026-03-20','Approved.',1,5,'2026-03-22','PO cleared.','STO-XYZ-26-018','SHP-26018',1,'2026-03-22','2026-03-23','TRK-DHL-031','2026-03-24',1,'COMPLETE','CLOSED','2026-03-24');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,rejection_reason,status,updated_at)
VALUES ('STO-DEMO-2026-010','2026-03-25',0,3,'ABC','ABC','XYZ',0,1,'Brian Scott','brian.scott@company.com','MAT-D032','Inactive Solvent Component',300,'L','Ambient',0,7800.00,0.00,0,'2026-04-08',0,0,2,'2026-03-26','Insufficient stock — only 80L available, 300L requested.','Insufficient stock at shipping site.','REJECTED','2026-03-26');


-- ── APRIL 2026 ────────────────────────────────────────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-011','2026-04-07',0,2,'ABL','ABL','XYZ',0,1,'Karen Bell','karen.bell@company.com','MAT-D033','API Active Ingredient Batch R25',260,'KG','2-8C',1,14500.00,1550.00,1,'2026-04-21',0,1,2,'2026-04-08','Confirmed.',1,5,'2026-04-12','Approved.','STO-ABL-26-024','SHP-26024',1,'2026-04-16','2026-04-17','TRK-DHL-033','2026-04-19',1,'COMPLETE','CLOSED','2026-04-19');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,actual_receipt_date,delivery_closed_out,corporate_sto_tracker_status,status,updated_at)
VALUES ('STO-DEMO-2026-012','2026-04-14',0,2,'XYZ','XYZ','ABC',0,1,'Rachel Tran','rachel.tran@company.com','MAT-D034','Drug Substance DS-95',65,'KG','-20C dry ice',1,31000.00,4700.00,1,'2026-04-28',1,1,2,'2026-04-15','Confirmed cold chain.',1,4,'2026-04-18','Approved.',1,5,'2026-04-21','PO issued.','STO-XYZ-26-025','SHP-26025',1,'2026-04-24','2026-04-25','TRK-FEDEX-034','2026-04-27',1,'COMPLETE','CLOSED','2026-04-27');

-- April: in-progress STOs (RECEIVING_LOGISTICS and FINANCE_REVIEW)
INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,finance_approved,finance_approved_by_user_id,finance_approved_at,finance_notes,sto_number,shipment_id,ready_to_ship,pgi_date,actual_ship_date,tracking_id,status,updated_at)
VALUES ('STO-DEMO-2026-013','2026-04-24',1,1,'ABC','ABC','ABL',0,1,'Alice Carter','alice.carter@company.com','MAT-D035','Stability Samples Q2 Urgent',120,'EA','2-8C',1,6900.00,580.00,1,'2026-04-30','Q2 stability programme start.',0,1,2,'2026-04-25','Confirmed.',1,5,'2026-04-27','Approved.','STO-ABC-26-031','SHP-26031',1,'2026-04-28','2026-04-29','TRK-UPS-035','RECEIVING_LOGISTICS','2026-04-29');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,sto_number,shipment_id,ready_to_ship,status,updated_at)
VALUES ('STO-DEMO-2026-014','2026-04-28',0,2,'ABL','ABL','ABC',0,1,'Henry Wu','henry.wu@company.com','MAT-D036','High Value Batch HV-02',48,'KG','-20C',1,43000.00,6100.00,1,'2026-05-12',1,1,2,'2026-04-29','Available.',1,4,'2026-05-01','Approved.','STO-ABL-26-029','SHP-26029',1,'FINANCE_REVIEW','2026-05-01');


-- ── MAY 2026 (current month — in-progress STOs) ───────────────────────────────

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,management_approved,management_approved_by_user_id,management_approved_at,management_notes,sto_number,shipment_id,ready_to_ship,status,updated_at)
VALUES ('STO-DEMO-2026-015','2026-05-05',0,2,'XYZ','XYZ','ABL',0,1,'Patrick James','patrick.james@company.com','MAT-D037','Compound DS-100 Phase III',55,'KG','-20C dry ice',1,48000.00,7200.00,1,'2026-05-20',1,1,2,'2026-05-06','Confirmed.',1,4,'2026-05-09','Approved — high priority.','STO-XYZ-26-031','SHP-26031',1,'MANAGEMENT_REVIEW','2026-05-09');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,planning_approved,planning_approved_by_user_id,planning_approved_at,planning_notes,sto_number,status,updated_at)
VALUES ('STO-DEMO-2026-016','2026-05-12',0,2,'ABC','ABC','XYZ',0,1,'Carol White','carol.white@company.com','MAT-D038','API Intermediate R26',290,'KG','2-8C',1,11200.00,1180.00,1,'2026-05-26',0,1,2,'2026-05-13','Confirmed available.','STO-ABC-26-038','SHIPPING_LOGISTICS','2026-05-13');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,rush_reason,management_approval_required,status,updated_at)
VALUES ('STO-DEMO-2026-017','2026-05-19',1,1,'ABL','ABL','XYZ',0,1,'Isabel Cruz','isabel.cruz@company.com','MAT-D039','Excipient HPMC K15M',900,'KG','Ambient',0,8700.00,720.00,0,'2026-05-27','Risk of line stoppage.',0,'PLANNING_REVIEW','2026-05-19');

INSERT INTO sto_requests (sto_id,request_date,rush_request,priority,requesting_plant,shipping_site,receiving_site,toll_mfg,requestor_user_id,requestor_name,requestor_email,material_sap,material_description,quantity,uom,shipping_conditions,controlled_shipping_required,material_value,freight_cost,insurance_loss_required,receiving_site_need_by_date,management_approval_required,status,updated_at)
VALUES ('STO-DEMO-2026-018','2026-05-26',0,3,'XYZ','XYZ','ABC',0,1,'Maria Evans','maria.evans@company.com','MAT-D040','Lactose Spray Dried',1000,'KG','Ambient',0,3100.00,280.00,0,'2026-06-10',0,'DRAFT','2026-05-26');


-- ============================================================
-- Audit log entries for all sample STOs
-- (Only key lifecycle events — CREATED + final status change)
-- ============================================================

INSERT INTO sto_audit_log (sto_request_id, action, old_status, new_status, performed_by, performed_by_name, notes, performed_at)
SELECT id, 'CREATED', NULL, 'DRAFT', requestor_user_id, requestor_name, NULL, request_date
FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%';

INSERT INTO sto_audit_log (sto_request_id, action, old_status, new_status, performed_by, performed_by_name, notes, performed_at)
SELECT id, 'SUBMITTED', 'DRAFT', 'PLANNING_REVIEW', requestor_user_id, requestor_name, NULL, DATEADD(day, 1, request_date)
FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' AND status <> 'DRAFT';

INSERT INTO sto_audit_log (sto_request_id, action, old_status, new_status, performed_by, performed_by_name, notes, performed_at)
SELECT id, 'PLANNING_APPROVED', 'PLANNING_REVIEW', 'SHIPPING_LOGISTICS', planning_approved_by_user_id, 'Shipping Site Planning', planning_notes, planning_approved_at
FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' AND planning_approved = 1;

INSERT INTO sto_audit_log (sto_request_id, action, old_status, new_status, performed_by, performed_by_name, notes, performed_at)
SELECT id, 'PLANNING_REJECTED', 'PLANNING_REVIEW', 'REJECTED', planning_approved_by_user_id, 'Shipping Site Planning', rejection_reason, planning_approved_at
FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' AND planning_approved = 0 AND status = 'REJECTED';

INSERT INTO sto_audit_log (sto_request_id, action, old_status, new_status, performed_by, performed_by_name, notes, performed_at)
SELECT id, 'FINANCE_APPROVED', 'FINANCE_REVIEW', 'RECEIVING_LOGISTICS', finance_approved_by_user_id, 'Finance', finance_notes, finance_approved_at
FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' AND finance_approved = 1;

INSERT INTO sto_audit_log (sto_request_id, action, old_status, new_status, performed_by, performed_by_name, notes, performed_at)
SELECT id, 'DELIVERY_CLOSED', 'RECEIVING_LOGISTICS', 'CLOSED', requestor_user_id, 'Receiving Site Logistics', 'Delivery confirmed and closed.', actual_receipt_date
FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' AND status = 'CLOSED';


-- ============================================================
-- Quick verification — run these to confirm the data loaded:
-- ============================================================
-- SELECT status, COUNT(*) AS cnt FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' GROUP BY status ORDER BY cnt DESC;
-- SELECT FORMAT(request_date,'yyyy-MM') AS month, COUNT(*) AS cnt FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' GROUP BY FORMAT(request_date,'yyyy-MM') ORDER BY month;
-- SELECT shipping_site, receiving_site, COUNT(*) AS cnt FROM sto_requests WHERE sto_id LIKE 'STO-DEMO-%' GROUP BY shipping_site, receiving_site ORDER BY cnt DESC;
